# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('pay_method', models.IntegerField(default=0)),
                ('pay_datetime', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('createuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField(default=1000)),
                ('integral', models.IntegerField(default=10000)),
                ('display', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_package', to='package.Package'),
        ),
    ]
