# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 08:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('cookies', models.TextField(null=True)),
                ('enable_cookie', models.IntegerField(default=0)),
                ('enable_review', models.IntegerField(default=0)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('delflag', models.IntegerField(default=0)),
                ('createuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_create_user', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_tag', to='tag.Tag')),
                ('updateuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
