# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='integral',
            field=models.IntegerField(default=0),
        ),
    ]
