# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integral', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cost',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'modules',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='cooperater',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='normal',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='provider',
        ),
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_role', to='profiles.Roles'),
        ),
        migrations.AddField(
            model_name='profile',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_role', to='profiles.Roles'),
        ),
        migrations.AddField(
            model_name='cost',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_cost_function', to='profiles.Modules'),
        ),
        migrations.AddField(
            model_name='cost',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_cost_role', to='profiles.Roles'),
        ),
    ]
