# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20180125_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cart',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_role', to='profiles.Roles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='review',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_role', to='profiles.Roles'),
        ),
    ]
