# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ab2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, null=True, verbose_name='URL')),
                ('asin', models.CharField(max_length=250, null=True, verbose_name='ASIN')),
                ('total', models.IntegerField(default=0, verbose_name='\u6b21\u6570')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('starttime', models.DateTimeField(null=True)),
                ('delflag', models.IntegerField(default=0)),
                ('finish', models.IntegerField(default=0)),
                ('sync_flag', models.IntegerField(default=0)),
                ('createuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab2_create_user', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ab2_tag', to='tag.Tag', verbose_name='\u5e73\u53f0')),
                ('updateuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ab2_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ab2',
            },
        ),
        migrations.CreateModel(
            name='Ab2_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('msg', models.TextField(null=True)),
                ('integral', models.IntegerField(default=10)),
                ('status', models.IntegerField(default=0)),
                ('option', models.IntegerField(default=0)),
                ('ab2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log2_ab', to='ab2.Ab2')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_ab2_account', to='account.Account')),
                ('createuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_ab2_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ab2_log',
            },
        ),
    ]
