# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-23 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ab2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ab2',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='ab2',
            name='keyword',
        ),
        migrations.AddField(
            model_name='ab2',
            name='url',
            field=models.CharField(max_length=500, null=True, verbose_name='URL'),
        ),
    ]
