# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ab',
            name='asin',
            field=models.CharField(max_length=250, null=True, verbose_name='ASIN'),
        ),
    ]
