# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('describe', models.TextField(null=True)),
                ('site', models.CharField(max_length=500, null=True)),
                ('integral', models.IntegerField(default=30)),
                ('display', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'integral',
            },
        ),
    ]
