# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integral', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Integra',
            new_name='Integral',
        ),
    ]
