# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.TextField(verbose_name='\u8bc4\u8bba'),
        ),
        migrations.AlterField(
            model_name='task',
            name='keyword',
            field=models.CharField(max_length=250, verbose_name='\u5173\u952e\u8bcd'),
        ),
        migrations.AlterField(
            model_name='task',
            name='mode',
            field=models.CharField(choices=[('A', 'ASIN'), ('S', 'SELLERID')], default='A', max_length=2, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_tag', to='tag.Tag', verbose_name='\u5e73\u53f0'),
        ),
        migrations.AlterField(
            model_name='task',
            name='total',
            field=models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u603b\u6570'),
        ),
    ]
