# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20180104_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finish',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='starttime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='keyword',
            field=models.CharField(max_length=250, verbose_name='Asin/SellerId'),
        ),
    ]
