# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_log',
            name='tag',
        ),
        migrations.AddField(
            model_name='task_log',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_task', to='task.Task'),
        ),
    ]
