# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20180112_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='review_flag',
            field=models.IntegerField(default=0),
        ),
    ]
