# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_review_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_log',
            name='reviewid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
