# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_log_reviewid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sync_flag',
            field=models.IntegerField(default=0),
        ),
    ]
