# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_sync_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_log',
            name='asin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task_log',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
