# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20180114_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_log',
            name='tid',
            field=models.IntegerField(null=True),
        ),
    ]
