# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20180124_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='task',
            name='name_type',
            field=models.IntegerField(choices=[(0, '\u9ed8\u8ba4\u59d3\u540d'), (1, '\u7537\u540d'), (2, '\u5973\u540d'), (3, '\u533f\u540d')], default='0', verbose_name='\u7559\u8bc4\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='option',
            field=models.IntegerField(choices=[(0, '\u81ea\u5bfc\u4e70\u624b\u53f7'), (1, '\u7cfb\u7edf\u4e70\u624b\u53f7 -- 150\u79ef\u5206/\u6b21')], default='0', verbose_name='\u8d26\u53f7\u7c7b\u578b'),
        ),
    ]
