# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_auto_20180130_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='option',
            field=models.IntegerField(choices=[(0, '\u81ea\u5bfc\u4e70\u624b\u53f7'), (1, '\u7cfb\u7edf\u4e70\u624b\u53f7 -- 100\u79ef\u5206/\u6b21')], default='0', verbose_name='\u8d26\u53f7\u7c7b\u578b'),
        ),
    ]
