# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_auto_20180202_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='keyword',
            field=models.CharField(max_length=250, verbose_name='Asin'),
        ),
    ]
