# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-21 22:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20180117_0726'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=250, null=True, verbose_name='Keyword')),
                ('total', models.IntegerField(default=0, verbose_name='\u6b21\u6570')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('starttime', models.DateTimeField(null=True)),
                ('delflag', models.IntegerField(default=0)),
                ('finish', models.IntegerField(default=0)),
                ('sync_flag', models.IntegerField(default=0)),
                ('createuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kw_create_user', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kw_tag', to='tag.Tag', verbose_name='\u5e73\u53f0')),
                ('updateuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kw_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kw',
            },
        ),
        migrations.CreateModel(
            name='Kw_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('msg', models.TextField(null=True)),
                ('integral', models.IntegerField(default=10)),
                ('status', models.IntegerField(default=0)),
                ('option', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_kw_account', to='account.Account')),
                ('createuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_kw_user', to=settings.AUTH_USER_MODEL)),
                ('kw', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_kw', to='kw.Kw')),
            ],
            options={
                'db_table': 'kw_log',
            },
        ),
    ]
