# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20180117_0726'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.IntegerField(choices=[(0, '\u81ea\u5bfc\u4e70\u624b\u53f7'), (1, '\u7cfb\u7edf\u4e70\u624b\u53f7 -- 150\u79ef\u5206/\u6b21')], default='0', max_length=2, verbose_name='\u8d26\u53f7\u7c7b\u578b')),
                ('asin', models.CharField(max_length=250, verbose_name='Asin')),
                ('total', models.IntegerField(default=0, verbose_name='\u52a0\u8d2d\u6b21\u6570')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('starttime', models.DateTimeField(null=True)),
                ('delflag', models.IntegerField(default=0)),
                ('finish', models.IntegerField(default=0)),
                ('sync_flag', models.IntegerField(default=0)),
                ('createuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_create_user', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_tag', to='tag.Tag', verbose_name='\u5e73\u53f0')),
                ('updateuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Cart_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('msg', models.TextField(null=True)),
                ('integral', models.IntegerField(default=10)),
                ('status', models.IntegerField(default=0)),
                ('option', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_cart_account', to='account.Account')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_task', to='cart.Cart')),
                ('createuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_cart_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart_log',
            },
        ),
    ]
