# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20180130_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='wish',
            field=models.IntegerField(choices=[(0, '\u4e0d\u52a0WISH'), (1, '\u81ea\u5bfc\u4e70\u624b\u53f7 -- 20\u79ef\u5206/\u6b21'), (2, '\u7cfb\u7edf\u4e70\u624b\u53f7 -- 50\u79ef\u5206/\u6b21')], default='0', verbose_name='\u662f\u5426\u52a0WISH'),
        ),
    ]
