# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='brand',
            field=models.CharField(max_length=250, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='cart',
            name='keyword',
            field=models.CharField(max_length=250, null=True, verbose_name='\u5173\u952e\u8bcd'),
        ),
        migrations.AddField(
            model_name='cart',
            name='sellerid',
            field=models.CharField(max_length=250, null=True, verbose_name='SellerId'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='wish',
            field=models.IntegerField(choices=[(0, '\u5426'), (1, '\u662f')], default='0', verbose_name='\u662f\u5426\u52a0WISH'),
        ),
    ]
